clc;
clear; 
close all; 

%% Set Network Objects
params = struct('lambda_m_O_pred', repmat(0.1,[11,1]), ...
                'lambda_m_O_succ', repmat(0.1,[11,1]), ...
                'lambda_m_R_pred', repmat(0.1,[11,1]), ...
                'lambda_m_R_succ', repmat(0.1,[11,1]), ...
                'lambda_T_F_pred', repmat(0.1,[11,1]), ...
                'lambda_T_F_succ', repmat(0.1,[11,1]), ...
                'lambda_T_R_pred', repmat(0.1,[11,1]), ...
                'lambda_T_R_succ', repmat(0.1,[11,1]), ...
                'm_O_pred_pred', repmat(0.1,[11,1]), ...
                'm_O_I_succ', repmat(0.1,[11,1]), ...
                'm_R_succ_succ', repmat(0.1,[11,1]), ...
                'm_R_I_pred', repmat(0.1,[11,1]), ...
                'T_F_pred_pred', repmat(0.1,[11,1]), ...
                'T_F_I_succ', repmat(0.1,[11,1]), ...
                'T_R_succ_succ', repmat(0.1,[11,1]), ...
                'T_R_I_pred', repmat(0.1,[11,1]), ...
                'delta_m_O_pred', 0, ...
                'delta_m_O_succ', 0, ...
                'delta_m_R_pred', 0, ...
                'delta_m_R_succ', 0, ...
                'delta_T_F_pred', 0, ...
                'delta_T_F_succ', 0, ...
                'delta_T_R_pred', 0, ...
                'delta_T_R_succ', 0);


% Set temperatures
T_set = 350;
T_amb = 273;

% Controller hyperparameters 
Ts = 1;
K = 10;
Q = 1; 

A = Household(true, false, T_set, Ts, K, Q, params, model, nmpcBlockPathName, busName);

%% Settings validation
% Define a random initial state and input
x0 = [1; 0; 0; 0; 0; 0]; 
mv0 = [0; 0; 0; 0; 0; 0; 0]; 

% Validation
paramList = {A};
validateFcns(A.nlobj, x0, mv0, [], paramList);
